name: rcuf-ecg
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - numpy<2
  - pandas<3
  - scipy<2
  - scikit-learn<2
  - pytorch>=2.1,<3
  - pyyaml>=6,<7
  - tqdm>=4.66,<5
  - pip
  - pip:
      - wfdb>=4.1,<5
